version: '3.7'
services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "companyreports"
    ports:
      - "3306:3306"
    volumes:
      - ~/docker/mysql:/var/lib/mysql
